name: slimgoose CI / CD
on: [push]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v2

      - name: Setup CI ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@PennameHq'
      - name: CI
        run: npm ci
      - name: Unit Tests
        run: npm run test:ci
  build-release:
    name: Build and Publish
    runs-on: ubuntu-latest
    if: (github.event_name == 'create' || github.event_name == 'push') && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      # and Publish to NPMJS
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org/'
      - name: Publish to NPMJS
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm config set scope "@penname"
          npm config list
          npm publish --access public
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
